---
default:
  image: node:22.15.0-alpine

stages:
  - lint
  - trigger

.setup-pnpm: &setup-pnpm
  - npm install -g corepack@latest
  - corepack enable
  - corepack prepare pnpm@10.6.2 --activate
  - pnpm config set store-dir .pnpm-store

lint:prettier+eslint:
  stage: lint
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  before_script:
    - *setup-pnpm
  script:
    - pnpm install
    - pnpm lint
    - pnpm fmt:ci

lint:circular-deps:
  stage: lint
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  before_script:
    - *setup-pnpm
  script:
    - pnpm install
    - pnpm deps:circular

lint:yaml:
  stage: lint
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  before_script:
    - apk add --no-cache yamllint
  script: yamllint .

lint:audit:
  stage: lint
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  before_script:
    - *setup-pnpm
  script:
    - pnpm audit --prod
  allow_failure: true

lint:commit:
  stage: lint
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  before_script:
    - apk add --no-cache git
    - npm install -g @commitlint/cli @commitlint/config-conventional
  script:
    - npx commitlint --from $CI_MERGE_REQUEST_DIFF_BASE_SHA --to HEAD --verbose

lint:unused-deps:
  stage: lint
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  before_script:
    # the office-addin-dev-certs plugin hard-codes sudo, which alpine does not
    # have by default.
    - apk add --no-cache git sudo
    - *setup-pnpm
    - pnpm install
  script:
    - pnpm knip --include dependencies

lint:shellcheck:
  stage: lint
  before_script:
    - apk update && apk add shellcheck git
  script:
    - git ls-files --exclude='*.sh' --ignored -c -z | xargs -0r shellcheck

lint:commit-signature:
  stage: lint
  needs: []
  rules:
    # Run in merge requests only.
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  before_script:
    - apk add --no-cache git gnupg
  script:
    # %G? will log signature information for a commit. `N` stands for "no signature", `B` for "bad signature"
    # refer to https://git-scm.com/docs/pretty-formats#Documentation/pretty-formats.txt-emGem
    # grep checks that the output does not contain any "N" or "B" characters.
    - >
      git log --format=format:'%G?' $CI_MERGE_REQUEST_DIFF_BASE_SHA..HEAD
      | tr -d '\n'
      | grep -q -v -e "N" -e "B"

trigger_changelog_preview:
  stage: trigger
  needs: []
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  variables:
    # We need to hard code the target repository since the pipeline is running in the forked repository
    PIPELINE_PROJECT_PATH: opentalk/frontend/web/web-app
    PIPELINE_MERGE_REQUEST_PROJECT_PATH: $CI_MERGE_REQUEST_SOURCE_PROJECT_PATH
    PIPELINE_MERGE_REQUEST_SOURCE_BRANCH_NAME: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    PIPELINE_MERGE_REQUEST_IID: $CI_MERGE_REQUEST_IID
  trigger: opentalk/tools/check-changelog
